---

- name: Default virtualization
  ansible.builtin.set_fact:
    __virtualization_type: "{{ ansible_facts.virtualization_type }}"

- name: Fix issue on github runner
  when: ansible_facts.virtualization_type == 'VirtualPC'
  block:

    - name: Get molecule driver
      ansible.builtin.set_fact:
        molecule_driver: "{{ lookup('env', 'MOLECULE_DRIVER_NAME') }}"

    - name: Redefine virtualization type
      ansible.builtin.set_fact:
        __virtualization_type: 'docker'
      when: molecule_driver | length > 0 and molecule_driver == 'docker'
