---

- name: Fix for /etc/hosts in docker container
  ansible.builtin.shell: |
    set -o pipefail
    if mount | grep -q /etc/hosts
    then
      cp /etc/hosts /tmp/hosts
      umount /etc/hosts
      cp /tmp/hosts /etc/hosts
    fi
  args:
    executable: /bin/bash
  changed_when: false
  when: ansible_virtualization_type in [ 'docker', 'container', 'containerd' ]

- name: Create list of addresses to register (default nic)  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    hosts_list: "{{ (hosts_list | default([])) + [ { 'name': item, 'ip': hostvars[item]['ansible_default_ipv4']['address'] } ] }}"
  loop: "{{ groups['all'] }}"
  when: hosts_adapter == 'default'

- name: Create list of addresses to register (custom nic)  # noqa jinja[spacing]
  ansible.builtin.set_fact:
    hosts_list: "{{ (hosts_list | default([])) + [ { 'name': item, 'ip': hostvars[item]['ansible_' + hosts_adapter]['ipv4']['address'] } ] }}"
  loop: "{{ groups['all'] }}"
  when: hosts_adapter != 'default'

- name: Register all nodes in /etc/hosts
  ansible.builtin.lineinfile:
    regexp: "{{ item.ip }}\\s +{{ item.name }}"
    line: "{{ item.ip }} {{ item.name }}"
    path: /etc/hosts
  loop: "{{ hosts_list }}"
