---

- name: Include hosts.yml
  ansible.builtin.include_tasks: hosts.yml
  when: hosts_mode is search('^(hosts|both)')

- name: Include dns.yml
  ansible.builtin.include_tasks: dns.yml
  when: hosts_mode is search('^(dns|both)')
