---

- name: Converge - post
  hosts: all
  tasks:
    - name: Get /etc/hosts
      command: cat /etc/hosts
      changed_when: false
      register: _hosts

    - name: Show /etc/hosts
      debug:
        var: _hosts.stdout_lines
