---

- name: Converge
  hosts: all
  vars:
  tasks:
    - name: Include role 'ansible-role-hosts'
      include_role:
        name: ansible-role-hosts

    - name: Get /etc/hosts
      command: cat /etc/hosts
      changed_when: false
      register: _hosts

    - name: Show /etc/hosts
      debug:
        var: _hosts.stdout_lines
